### ISSUE TITLE
running example gives: "ModuleNotFoundError: No module named 'mopo.env'"

### ISSUE THREAD

**Issue by capybaralet** [tianheyu927/mopo#2]
And it looks to me like this module is indeed missing.
Traceback:

```
(mopo) capybara@blg4101:~/mopo$ mopo run_local examples.development --config=examples.config.d4rl.halfcheetah_mixed --gpus=1 --trial-gpus=1
WARNING: Logging before flag parsing goes to stderr.
W0909 03:02:30.004770 47483036384896 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /home/capybara/anaconda3/envs/mopo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py -I/home/capybara/.mujoco/mujoco200/include -I/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/numpy/core/include -I/home/capybara/anaconda3/envs/mopo/include/python3.6m -c /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/cymj.c -o /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /home/capybara/anaconda3/envs/mopo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py -I/home/capybara/.mujoco/mujoco200/include -I/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/numpy/core/include -I/home/capybara/anaconda3/envs/mopo/include/python3.6m -c /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.c -o /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
creating /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6
creating /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py
gcc -pthread -shared -B /home/capybara/anaconda3/envs/mopo/compiler_compat -L/home/capybara/anaconda3/envs/mopo/lib -Wl,-rpath=/home/capybara/anaconda3/envs/mopo/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/cymj.o /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -L/home/capybara/.mujoco/mujoco200/bin -Wl,-R/home/capybara/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
Traceback (most recent call last):
  File "/home/capybara/anaconda3/envs/mopo/bin/mopo", line 33, in <module>
    sys.exit(load_entry_point('mopo', 'console_scripts', 'mopo')())
  File "/home/capybara/mopo/softlearning/scripts/console_scripts.py", line 202, in main
    return cli()
  File "/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/capybara/anaconda3/envs/mopo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/capybara/mopo/softlearning/scripts/console_scripts.py", line 71, in run_example_local_cmd
    return run_example_local(example_module_name, example_argv)
  File "/home/capybara/mopo/examples/instrument.py", line 209, in run_example_local
    example_args = example_module.get_parser().parse_args(example_argv)
  File "/home/capybara/mopo/examples/development/__init__.py", line 37, in get_parser
    from examples.utils import get_parser
  File "/home/capybara/mopo/examples/utils.py", line 9, in <module>
    import softlearning.environments.utils as env_utils
  File "/home/capybara/mopo/softlearning/environments/utils.py", line 6, in <module>
    import mopo.env as env_overwrite
ModuleNotFoundError: No module named 'mopo.env'

```

**Comment by tianheyu927** [comment]
Did you run `pip install -e .` from the base directory of `mopo`?

**Comment by capybaralet** [comment]
Yes.  And if I modify `/home/capybara/mopo/softlearning/environments/utils.py` to remove this import and where it is called, the code seems to be working fine.

**Comment by capybaralet** [comment]
Before closing, can you confirm that this is an acceptable way to resolve the issue?
https://github.com/tianheyu927/mopo/compare/master...capybaralet:patch-1

Or would that break anything?

**Comment by tianheyu927** [comment]
It's a bit strange that you get this import error, but removing that won't break anything.
